### ISSUE TITLE
iwyu 0.7 for clang-3.9 is out

### ISSUE THREAD

**Issue by larseggert** [jasonmp85/homebrew-iwyu#12]
Any chance this could be updated?
https://include-what-you-use.org/downloads/

**Comment by jasonmp85** [comment]
Been meaning to for some time 😆

![screen shot 2017-01-11 at 1 13 35 pm](https://cloud.githubusercontent.com/assets/50673/21864620/d2175844-d7ff-11e6-9f5a-7f617b154df8.png)

**Comment by jasonmp85** [comment]
FWIW the latest `iwyu` should make it more palatable to Homebrew proper, so I've also opened Homebrew/homebrew-core#8751. If it's accepted, I'll deprecate this tap.

**Comment by jasonmp85** [comment]
OK, released this (Homebrew version `0.7`, tagged here as `5.0.0`).

Closing for now; let me know whether this works as expected, as I overhauled quite a bit. The upstream formula's not looking likely, but I might have some time to generate an in-tree build at some point and see whether I can work that into `homebrew-core`.
